
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// GAME
export const RESET_GAME = "RESET_GAME";
export const ADDTABLE_GAME_SUCCESS = "ADDTABLE_GAME_SUCCESS";
export const CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS";
export const DELETE_GAME_SUCCESS = "DELETE_GAME_SUCCESS";
export const FINDBYGAMETABLES_GAME_SUCCESS = "FINDBYGAMETABLES_GAME_SUCCESS";
export const GET_GAME_SUCCESS = "GET_GAME_SUCCESS";
export const LIST_GAME_SUCCESS = "LIST_GAME_SUCCESS";
export const PAUSE_GAME_SUCCESS = "PAUSE_GAME_SUCCESS";
export const STOP_GAME_SUCCESS = "STOP_GAME_SUCCESS";
export const UPDATE_GAME_SUCCESS = "UPDATE_GAME_SUCCESS";

// PLAYER
export const RESET_PLAYER = "RESET_PLAYER";
export const KNOCKOUT_PLAYER_SUCCESS = "KNOCKOUT_PLAYER_SUCCESS";
export const CREATE_PLAYER_SUCCESS = "CREATE_PLAYER_SUCCESS";
export const DELETE_PLAYER_SUCCESS = "DELETE_PLAYER_SUCCESS";
export const GET_PLAYER_SUCCESS = "GET_PLAYER_SUCCESS";
export const LIST_PLAYER_SUCCESS = "LIST_PLAYER_SUCCESS";
export const UPDATE_PLAYER_SUCCESS = "UPDATE_PLAYER_SUCCESS";

// TABLE
export const RESET_TABLE = "RESET_TABLE";
export const ADDPLAYERTOTABLE_TABLE_SUCCESS = "ADDPLAYERTOTABLE_TABLE_SUCCESS";
export const LISTTABLEPLAYERS_TABLE_SUCCESS = "LISTTABLEPLAYERS_TABLE_SUCCESS";
export const CREATE_TABLE_SUCCESS = "CREATE_TABLE_SUCCESS";
export const DELETE_TABLE_SUCCESS = "DELETE_TABLE_SUCCESS";
export const FINDBYPLAYERSLIST_TABLE_SUCCESS = "FINDBYPLAYERSLIST_TABLE_SUCCESS";
export const FINDBYTABLEPLAYER_TABLE_SUCCESS = "FINDBYTABLEPLAYER_TABLE_SUCCESS";
export const GET_TABLE_SUCCESS = "GET_TABLE_SUCCESS";
export const LIST_TABLE_SUCCESS = "LIST_TABLE_SUCCESS";
export const UPDATE_TABLE_SUCCESS = "UPDATE_TABLE_SUCCESS";

// USER
export const RESET_USER = "RESET_USER";
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
